il_mode: CIT

dataset: safety_alignment_llama2_task2
classification_type: sentence-level
metric_for_each_task: ['jailbreak-rate','jailbreak-rate']


classifier: None

method: SEQ

training_epochs_list: [10, 30]
backbone_max_new_token_list: [32, 32]
max_seq_length: 256


lr: 5e-5 
batch_size: 10
gradient_accumulation_steps: 1

info_per_steps: 25
is_evaluate_init: True
evaluate_interval: 10

prompt_type: auto